apiVersion: v1
kind: Secret
metadata:
    name: wordpress-secret
type: Opaque
data:
    mysql-username: d3BHSDliMzhUWnNBSkJOVQ==
    mysql-password: eHUybVFxd3FWSmhZOGhNUQ==
    mysql-db: NGtCZWdDQU00YTRGQ1NiYQ==
    mysql-root-password: R1RCNm1NYzZxNEJaUHQ1NQ==
